# Generated by Django
from django.db import migrations
import json

def populate_components(apps, schema_editor):
    Component = apps.get_model('pcbuilder', 'Component')
    Category = apps.get_model('pcbuilder', 'Category')
    Vendor = apps.get_model('pcbuilder', 'Vendor')
    
    # Create categories if they don't exist
    categories_data = [
        {'name': 'CPU', 'slug': 'cpu', 'icon': 'cpu'},
        {'name': 'Motherboard', 'slug': 'motherboard', 'icon': 'motherboard'},
        {'name': 'GPU', 'slug': 'gpu', 'icon': 'gpu'},
        {'name': 'RAM', 'slug': 'ram', 'icon': 'ram'},
        {'name': 'Storage', 'slug': 'storage', 'icon': 'storage'},
        {'name': 'Power Supply', 'slug': 'psu', 'icon': 'psu'},
        {'name': 'Case', 'slug': 'case', 'icon': 'case'},
        {'name': 'CPU Cooler', 'slug': 'cooler', 'icon': 'cooler'},
    ]
    
    categories = {}
    for cat_data in categories_data:
        category, created = Category.objects.get_or_create(
            slug=cat_data['slug'],
            defaults=cat_data
        )
        categories[cat_data['slug']] = category
    
    # Create vendors if they don't exist
    vendors_data = [
        {'name': 'Intel', 'website': 'https://intel.com', 'logo': 'intel.png'},
        {'name': 'AMD', 'website': 'https://amd.com', 'logo': 'amd.png'},
        {'name': 'NVIDIA', 'website': 'https://nvidia.com', 'logo': 'nvidia.png'},
        {'name': 'ASUS', 'website': 'https://asus.com', 'logo': 'asus.png'},
        {'name': 'MSI', 'website': 'https://msi.com', 'logo': 'msi.png'},
        {'name': 'Gigabyte', 'website': 'https://gigabyte.com', 'logo': 'gigabyte.png'},
        {'name': 'Corsair', 'website': 'https://corsair.com', 'logo': 'corsair.png'},
        {'name': 'Samsung', 'website': 'https://samsung.com', 'logo': 'samsung.png'},
        {'name': 'Western Digital', 'website': 'https://westerndigital.com', 'logo': 'wd.png'},
        {'name': 'NZXT', 'website': 'https://nzxt.com', 'logo': 'nzxt.png'},
        {'name': 'Cooler Master', 'website': 'https://coolermaster.com', 'logo': 'cm.png'},
        {'name': 'EVGA', 'website': 'https://evga.com', 'logo': 'evga.png'},
        {'name': 'Seasonic', 'website': 'https://seasonic.com', 'logo': 'seasonic.png'},
        {'name': 'Crucial', 'website': 'https://crucial.com', 'logo': 'crucial.png'},
        {'name': 'Kingston', 'website': 'https://kingston.com', 'logo': 'kingston.png'},
        {'name': 'G.Skill', 'website': 'https://gskill.com', 'logo': 'gskill.png'},
        {'name': 'Lian Li', 'website': 'https://lian-li.com', 'logo': 'lianli.png'},
        {'name': 'Noctua', 'website': 'https://noctua.at', 'logo': 'noctua.png'},
    ]
    
    vendors = {}
    for vendor_data in vendors_data:
        vendor, created = Vendor.objects.get_or_create(
            name=vendor_data['name'],
            defaults=vendor_data
        )
        vendors[vendor_data['name']] = vendor
    
    # Component data
    components_data = [
        # CPUs
        {
            'name': 'Intel Core i9-13900K',
            'description': '24-core (8P + 16E) Desktop Processor',
            'price': 569.99,
            'image': 'https://via.placeholder.com/300x300/1f2937/ffffff?text=Intel+i9-13900K',
            'specs': json.dumps({
                'socket': 'LGA1700',
                'cores': 24,
                'threads': 32,
                'base_clock': 3.0,
                'boost_clock': 5.8,
                'tdp': 253
            }),
            'stock': 15,
            'category': categories['cpu'],
            'vendor': vendors['Intel']
        },
        {
            'name': 'Intel Core i7-13700K',
            'description': '16-core (8P + 8E) Desktop Processor',
            'price': 399.99,
            'image': 'https://via.placeholder.com/300x300/1f2937/ffffff?text=Intel+i7-13700K',
            'specs': json.dumps({
                'socket': 'LGA1700',
                'cores': 16,
                'threads': 24,
                'base_clock': 3.4,
                'boost_clock': 5.4,
                'tdp': 253
            }),
            'stock': 25,
            'category': categories['cpu'],
            'vendor': vendors['Intel']
        },
        {
            'name': 'Intel Core i5-13600K',
            'description': '14-core (6P + 8E) Desktop Processor',
            'price': 319.99,
            'image': 'https://via.placeholder.com/300x300/1f2937/ffffff?text=Intel+i5-13600K',
            'specs': json.dumps({
                'socket': 'LGA1700',
                'cores': 14,
                'threads': 20,
                'base_clock': 3.5,
                'boost_clock': 5.1,
                'tdp': 181
            }),
            'stock': 30,
            'category': categories['cpu'],
            'vendor': vendors['Intel']
        },
        {
            'name': 'AMD Ryzen 9 7950X',
            'description': '16-core 32-thread Desktop Processor',
            'price': 699.99,
            'image': 'https://via.placeholder.com/300x300/ed8936/ffffff?text=AMD+Ryzen+9+7950X',
            'specs': json.dumps({
                'socket': 'AM5',
                'cores': 16,
                'threads': 32,
                'base_clock': 4.5,
                'boost_clock': 5.7,
                'tdp': 170
            }),
            'stock': 10,
            'category': categories['cpu'],
            'vendor': vendors['AMD']
        },
        {
            'name': 'AMD Ryzen 7 7700X',
            'description': '8-core 16-thread Desktop Processor',
            'price': 399.99,
            'image': 'https://via.placeholder.com/300x300/ed8936/ffffff?text=AMD+Ryzen+7+7700X',
            'specs': json.dumps({
                'socket': 'AM5',
                'cores': 8,
                'threads': 16,
                'base_clock': 4.5,
                'boost_clock': 5.4,
                'tdp': 105
            }),
            'stock': 20,
            'category': categories['cpu'],
            'vendor': vendors['AMD']
        },
        
        # Motherboards
        {
            'name': 'ASUS ROG STRIX Z790-E GAMING',
            'description': 'Intel Z790 ATX Gaming Motherboard',
            'price': 449.99,
            'image': 'https://via.placeholder.com/300x300/374151/ffffff?text=ASUS+ROG+Z790-E',
            'specs': json.dumps({
                'socket': 'LGA1700',
                'form_factor': 'ATX',
                'chipset': 'Z790',
                'memory_slots': 4,
                'max_memory': 128
            }),
            'stock': 12,
            'category': categories['motherboard'],
            'vendor': vendors['ASUS']
        },
        {
            'name': 'MSI MPG B760I EDGE WIFI',
            'description': 'Intel B760 Mini-ITX Gaming Motherboard',
            'price': 199.99,
            'image': 'https://via.placeholder.com/300x300/374151/ffffff?text=MSI+MPG+B760I',
            'specs': json.dumps({
                'socket': 'LGA1700',
                'form_factor': 'ITX',
                'chipset': 'B760',
                'memory_slots': 2,
                'max_memory': 64
            }),
            'stock': 18,
            'category': categories['motherboard'],
            'vendor': vendors['MSI']
        },
        {
            'name': 'Gigabyte X670E AORUS MASTER',
            'description': 'AMD X670E ATX Gaming Motherboard',
            'price': 499.99,
            'image': 'https://via.placeholder.com/300x300/374151/ffffff?text=Gigabyte+X670E',
            'specs': json.dumps({
                'socket': 'AM5',
                'form_factor': 'ATX',
                'chipset': 'X670E',
                'memory_slots': 4,
                'max_memory': 128
            }),
            'stock': 8,
            'category': categories['motherboard'],
            'vendor': vendors['Gigabyte']
        },
        
        # GPUs
        {
            'name': 'NVIDIA GeForce RTX 4090',
            'description': '24GB GDDR6X Graphics Card',
            'price': 1599.99,
            'image': 'https://via.placeholder.com/300x300/76a9fa/ffffff?text=NVIDIA+RTX+4090',
            'specs': json.dumps({
                'length': 380,
                'tdp': 450,
                'memory': 24,
                'memory_type': 'GDDR6X',
                'boost_clock': 2520
            }),
            'stock': 5,
            'category': categories['gpu'],
            'vendor': vendors['NVIDIA']
        },
        {
            'name': 'NVIDIA GeForce RTX 4080',
            'description': '16GB GDDR6X Graphics Card',
            'price': 1199.99,
            'image': 'https://via.placeholder.com/300x300/76a9fa/ffffff?text=NVIDIA+RTX+4080',
            'specs': json.dumps({
                'length': 340,
                'tdp': 320,
                'memory': 16,
                'memory_type': 'GDDR6X',
                'boost_clock': 2505
            }),
            'stock': 12,
            'category': categories['gpu'],
            'vendor': vendors['NVIDIA']
        },
        {
            'name': 'NVIDIA GeForce RTX 4070 Ti',
            'description': '12GB GDDR6X Graphics Card',
            'price': 799.99,
            'image': 'https://via.placeholder.com/300x300/76a9fa/ffffff?text=NVIDIA+RTX+4070+Ti',
            'specs': json.dumps({
                'length': 285,
                'tdp': 285,
                'memory': 12,
                'memory_type': 'GDDR6X',
                'boost_clock': 2610
            }),
            'stock': 20,
            'category': categories['gpu'],
            'vendor': vendors['NVIDIA']
        },
        {
            'name': 'AMD Radeon RX 7900 XTX',
            'description': '24GB GDDR6 Graphics Card',
            'price': 999.99,
            'image': 'https://via.placeholder.com/300x300/ed8936/ffffff?text=AMD+RX+7900+XTX',
            'specs': json.dumps({
                'length': 287,
                'tdp': 355,
                'memory': 24,
                'memory_type': 'GDDR6',
                'boost_clock': 2500
            }),
            'stock': 8,
            'category': categories['gpu'],
            'vendor': vendors['AMD']
        },
        
        # RAM
        {
            'name': 'Corsair Vengeance RGB Pro 32GB',
            'description': 'DDR4-3600 CL18 Memory Kit (2x16GB)',
            'price': 129.99,
            'image': 'https://via.placeholder.com/300x300/10b981/ffffff?text=Corsair+Vengeance+32GB',
            'specs': json.dumps({
                'capacity': 32,
                'speed': 3600,
                'latency': 18,
                'type': 'DDR4',
                'modules': 2
            }),
            'stock': 50,
            'category': categories['ram'],
            'vendor': vendors['Corsair']
        },
        {
            'name': 'G.Skill Trident Z5 RGB 32GB',
            'description': 'DDR5-6000 CL36 Memory Kit (2x16GB)',
            'price': 199.99,
            'image': 'https://via.placeholder.com/300x300/10b981/ffffff?text=G.Skill+Trident+Z5+32GB',
            'specs': json.dumps({
                'capacity': 32,
                'speed': 6000,
                'latency': 36,
                'type': 'DDR5',
                'modules': 2
            }),
            'stock': 25,
            'category': categories['ram'],
            'vendor': vendors['G.Skill']
        },
        
        # Storage
        {
            'name': 'Samsung 970 EVO Plus 1TB',
            'description': 'NVMe M.2 SSD with V-NAND Technology',
            'price': 89.99,
            'image': 'https://via.placeholder.com/300x300/1f2937/ffffff?text=Samsung+970+EVO+1TB',
            'specs': json.dumps({
                'capacity': 1000,
                'type': 'NVMe',
                'read_speed': 3500,
                'write_speed': 3300,
                'form_factor': 'M.2'
            }),
            'stock': 40,
            'category': categories['storage'],
            'vendor': vendors['Samsung']
        },
        {
            'name': 'Western Digital Black SN850X 2TB',
            'description': 'NVMe M.2 SSD with PCIe 4.0',
            'price': 179.99,
            'image': 'https://via.placeholder.com/300x300/1f2937/ffffff?text=WD+Black+SN850X+2TB',
            'specs': json.dumps({
                'capacity': 2000,
                'type': 'NVMe',
                'read_speed': 7300,
                'write_speed': 6600,
                'form_factor': 'M.2'
            }),
            'stock': 15,
            'category': categories['storage'],
            'vendor': vendors['Western Digital']
        },
        
        # Power Supplies
        {
            'name': 'Corsair RM850x',
            'description': '850W 80+ Gold Fully Modular Power Supply',
            'price': 149.99,
            'image': 'https://via.placeholder.com/300x300/f59e0b/ffffff?text=Corsair+RM850x',
            'specs': json.dumps({
                'wattage': 850,
                'efficiency': '80+ Gold',
                'modular': 'Fully Modular',
                'form_factor': 'ATX'
            }),
            'stock': 30,
            'category': categories['psu'],
            'vendor': vendors['Corsair']
        },
        {
            'name': 'Seasonic Focus GX-1000',
            'description': '1000W 80+ Gold Fully Modular Power Supply',
            'price': 199.99,
            'image': 'https://via.placeholder.com/300x300/f59e0b/ffffff?text=Seasonic+Focus+GX-1000',
            'specs': json.dumps({
                'wattage': 1000,
                'efficiency': '80+ Gold',
                'modular': 'Fully Modular',
                'form_factor': 'ATX'
            }),
            'stock': 20,
            'category': categories['psu'],
            'vendor': vendors['Seasonic']
        },
        
        # Cases
        {
            'name': 'NZXT H510 Flow',
            'description': 'ATX Mid Tower Case with Mesh Front Panel',
            'price': 89.99,
            'image': 'https://via.placeholder.com/300x300/6b7280/ffffff?text=NZXT+H510+Flow',
            'specs': json.dumps({
                'form_factor': 'ATX',
                'max_gpu_length': 360,
                'max_cpu_cooler_height': 165,
                'fans_included': 2,
                'material': 'Steel'
            }),
            'stock': 35,
            'category': categories['case'],
            'vendor': vendors['NZXT']
        },
        {
            'name': 'Lian Li O11 Dynamic EVO',
            'description': 'ATX Mid Tower Case with Tempered Glass',
            'price': 169.99,
            'image': 'https://via.placeholder.com/300x300/6b7280/ffffff?text=Lian+Li+O11+Dynamic+EVO',
            'specs': json.dumps({
                'form_factor': 'ATX',
                'max_gpu_length': 420,
                'max_cpu_cooler_height': 167,
                'fans_included': 0,
                'material': 'Aluminum'
            }),
            'stock': 15,
            'category': categories['case'],
            'vendor': vendors['Lian Li']
        },
        
        # CPU Coolers
        {
            'name': 'Noctua NH-D15',
            'description': 'Dual-Tower CPU Cooler with 140mm Fans',
            'price': 99.99,
            'image': 'https://via.placeholder.com/300x300/059669/ffffff?text=Noctua+NH-D15',
            'specs': json.dumps({
                'height': 165,
                'type': 'Air',
                'fans': 2,
                'fan_size': 140,
                'noise_level': 24.6
            }),
            'stock': 25,
            'category': categories['cooler'],
            'vendor': vendors['Noctua']
        },
        {
            'name': 'Corsair H150i ELITE CAPELLIX',
            'description': '360mm Liquid CPU Cooler with RGB',
            'price': 189.99,
            'image': 'https://via.placeholder.com/300x300/059669/ffffff?text=Corsair+H150i+ELITE',
            'specs': json.dumps({
                'height': 52,
                'type': 'Liquid',
                'radiator_size': 360,
                'fans': 3,
                'fan_size': 120
            }),
            'stock': 12,
            'category': categories['cooler'],
            'vendor': vendors['Corsair']
        },
    ]
    
    # Create components
    for comp_data in components_data:
        Component.objects.get_or_create(
            name=comp_data['name'],
            defaults=comp_data
        )

def reverse_populate_components(apps, schema_editor):
    Component = apps.get_model('pcbuilder', 'Component')
    Component.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('pcbuilder', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RunPython(populate_components, reverse_populate_components),
    ] 